config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :pastes, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/paste.rb
class Paste < ApplicationRecord
	before_create :set_uuid

	validates :id, uniqueness: true
	validates_presence_of :expiration_length_in_minutes
	validates_presence_of :content

	def set_uuid
		self.id = SecureRandom.uuid
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pastes_controller.rb
class PastesController < ApplicationController
  before_action :set_paste, only: [ :show, :destroy ]
  before_action :get_params_to_select_field, only: [:create]

  # GET /pastes or /pastes.json
  def index
    @pastes = Paste.all
  end

  # GET /pastes/1 or /pastes/1.json
  def show
  end

  # GET /pastes/new
  def new
    @paste = Paste.new
  end

  # GET /pastes/1/edit
  def edit
  end

  # POST /pastes or /pastes.json
  def create
    @paste = Paste.new(paste_params)

    respond_to do |format|
      if @paste.save
        format.html { redirect_to @paste, notice: "Paste was successfully created." }
        format.json { render :show, status: :created, location: @paste }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paste.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pastes/1 or /pastes/1.json
  def update
    respond_to do |format|
      if @paste.update(paste_params)
        format.html { redirect_to @paste, notice: "Paste was successfully updated." }
        format.json { render :show, status: :ok, location: @paste }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @paste.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pastes/1 or /pastes/1.json
  def destroy
    @paste.destroy
    respond_to do |format|
      format.html { redirect_to pastes_url, notice: "Paste was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paste
      @paste = Paste.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def paste_params
      params.require(:paste).permit(:expiration_length_in_minutes, :content)
    end

    def get_params_to_select_field
      @select_param = paste_params[:expiration_length_in_minutes]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pastes_helper.rb
module PastesHelper
	def options_for_expiration_length_in_minutes
		{
			'05 minutes'  => 5,
			'10 minutes' => 10,
			'15 minutes' => 15,
			'30 minutes' => 30,
			'60 minutes' => 60
		}
	end
end

app/views/home/index.html.erb
<header class="row">
	<div class="col-lg-12">
		<%= image_tag 'serenity.svg', class: 'img-center' %>
	</div>
</header>
<section class="row">
	<div class="col-lg-12 text-center content-section">
		<%= link_to 'Começar', new_paste_path, class: 'btn btn-custom', role: 'button' %>
	</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmallUrl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pastes/_form.html.erb
<%= form_with(model: paste, local: true) do |f| %>
  <div class="row">
    <div class="col-lg-12">
      <%= render partial: 'form_errors', locals: { resource: paste } %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3">
      <div class="form-group">
        <%= f.label 'Expiration' %>
        <%= f.select :expiration_length_in_minutes, options_for_select(options_for_expiration_length_in_minutes, selected: (@select_param if @select_param.present?)), { include_blank: 'Select...' }, class: 'custom-select form-control' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: 'form-control', rows: 25 %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to 'Cancelar', root_path, class: 'btn btn-light', role: 'button' %>
    </div>
  </div>
<% end %>

app/views/pastes/_form_errors.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Alert!</h4>
    <p><%= pluralize(resource.errors.count, "error") %> prohibited this <%= resource.class.name.downcase %> from being saved:</p>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <hr>
    <p class="mb-0">You must enter valid information before you can continue.</p>
  </div>
<% end %>

app/views/pastes/edit.html.erb
<h1>Editing Paste</h1>

<%= render 'form', paste: @paste %>

<%= link_to 'Show', @paste %> |
<%= link_to 'Back', pastes_path %>

app/views/pastes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pastes</h1>

<table>
  <thead>
    <tr>
      <th>Expiration length in minutes</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pastes.each do |paste| %>
      <tr>
        <td><%= paste.expiration_length_in_minutes %></td>
        <td><%= paste.content %></td>
        <td><%= link_to 'Show', paste %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paste', new_paste_path %>

app/views/pastes/new.html.erb
<h1>New Paste</h1>
<%= render 'form', paste: @paste %>

app/views/pastes/show.html.erb
<strong>Content:</strong>
<p>
  <%= @paste.content %>
</p>